const GLOBAL_ROLES = [
  'Accountant', 'Accounts Executive', 'Accounts Manager', 'Account Manager', 'Actuary',
  'AI Engineer', 'AI Specialist', 'AI Research Scientist', 'Analyst', 'Android Developer',
  'Application Developer', 'Architect', 'Artificial Intelligence Engineer', 'Assistant Manager',
  'Assistant Professor', 'Associate Director', 'Associate Engineer', 'Audit Associate',
  'Auditor', 'Automation Engineer', 'Backend Developer', 'Big Data Engineer', 'Biomedical Engineer',
  'Business Analyst', 'Business Development Executive', 'Business Development Manager',
  'Chief Executive Officer (CEO)', 'Chief Financial Officer (CFO)', 'Chief Technology Officer (CTO)',
  'Civil Engineer', 'Cloud Architect', 'Cloud Engineer', 'Cloud Solutions Engineer',
  'Consultant', 'Content Writer', 'Cyber Security Analyst', 'Data Analyst', 'Data Engineer',
  'Data Scientist', 'Database Administrator', 'Design Engineer', 'DevOps Engineer',
  'Digital Marketing Executive', 'Digital Marketing Manager', 'Director', 'Electrical Engineer',
  'Embedded Systems Engineer', 'Engineering Manager', 'Entrepreneur', 'Executive Assistant',
  'Finance Manager', 'Financial Analyst', 'Founder & CEO', 'Frontend Developer',
  'Full Stack Developer', 'General Manager', 'Graphic Designer', 'HR Executive',
  'HR Manager', 'HR Recruiter', 'Human Resources Business Partner (HRBP)', 'Industrial Engineer',
  'Information Security Analyst', 'iOS Developer', 'IT Consultant', 'IT Support Specialist',
  'Java Developer', 'Lead Engineer', 'Machine Learning Engineer', 'Marketing Executive',
  'Marketing Manager', 'Mechanical Engineer', 'Network Engineer', 'Operations Manager',
  'Product Designer', 'Product Manager', 'Product Owner', 'Project Coordinator',
  'Project Manager', 'Python Developer', 'Quality Assurance (QA) Engineer', 'Quality Engineer',
  'Research Analyst', 'Research Assistant', 'Research Associate', 'Research Scientist',
  'Sales Executive', 'Sales Manager', 'Scrum Master', 'Senior Accountant',
  'Senior Business Analyst', 'Senior Data Engineer', 'Senior Data Scientist',
  'Senior DevOps Engineer', 'Senior Full Stack Developer', 'Senior HR Manager',
  'Senior Product Manager', 'Senior Software Engineer', 'Senior Systems Engineer',
  'Software Developer', 'Software Development Engineer (SDE)', 'Software Development Engineer II (SDE-II)',
  'Software Development Engineer III (SDE-III)', 'Software Engineer', 'Software Test Engineer',
  'Solutions Architect', 'System Administrator', 'Systems Engineer', 'Talent Acquisition Specialist',
  'Tax Consultant', 'Technical Lead', 'Technical Writer', 'UI/UX Designer',
  'UX Researcher', 'Vice President', 'Web Developer'
];

module.exports = { GLOBAL_ROLES };
